/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminEventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/event-types/{eventTypeId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminSlots_generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AdminEventTypes_update"];
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Bookings_list"];
        put?: never;
        post: operations["Bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EventTypes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types/{eventTypeId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Slots_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EventTypes_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OwnerOps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BookingCreateInput: {
            eventTypeId: string;
            slotStart: string;
            slotEnd: string;
            guestName?: string;
            guestContact?: string;
        };
        /**
         * @example {
         *       "eventTypeId": "550e8400-e29b-41d4-a716-446655440000",
         *       "slotStart": "2025-06-01T10:00:00Z",
         *       "slotEnd": "2025-06-01T10:30:00Z",
         *       "guestName": "Иван Петров",
         *       "guestContact": "ivan@example.com"
         *     }
         */
        BookingCreateInputExample: {
            eventTypeId: string;
            slotStart: string;
            slotEnd: string;
            guestName?: string;
            guestContact?: string;
        };
        /**
         * @example {
         *       "id": "770e8400-e29b-41d4-a716-446655440002",
         *       "eventTypeId": "550e8400-e29b-41d4-a716-446655440000",
         *       "slotStart": "2025-06-01T10:00:00Z",
         *       "slotEnd": "2025-06-01T10:30:00Z",
         *       "guestName": "Иван Петров",
         *       "guestContact": "ivan@example.com",
         *       "createdAt": "2025-05-20T12:00:00Z"
         *     }
         */
        "Calendar.Domain.Booking": {
            id: string;
            eventTypeId: string;
            slotStart: string;
            slotEnd: string;
            guestName?: string;
            guestContact?: string;
            createdAt: string;
        };
        /**
         * @example {
         *       "id": "550e8400-e29b-41d4-a716-446655440000",
         *       "name": "Консультация",
         *       "description": "Индивидуальная консультация",
         *       "durationMinutes": 30,
         *       "ownerId": "11111111-1111-1111-1111-111111111111"
         *     }
         */
        "Calendar.Domain.EventType": {
            id: string;
            name: string;
            description?: string;
            /** Format: int32 */
            durationMinutes: number;
            ownerId: string;
        };
        /**
         * @example {
         *       "id": "11111111-1111-1111-1111-111111111111",
         *       "name": "Алексей Смирнов",
         *       "email": "alexey@example.com"
         *     }
         */
        "Calendar.Domain.Owner": {
            id: string;
            name: string;
            email?: string;
        };
        /**
         * @example {
         *       "id": "660e8400-e29b-41d4-a716-446655440001",
         *       "eventTypeId": "550e8400-e29b-41d4-a716-446655440000",
         *       "startAt": "2025-06-01T10:00:00Z",
         *       "endAt": "2025-06-01T10:30:00Z",
         *       "status": "free"
         *     }
         */
        "Calendar.Domain.Slot": {
            id: string;
            eventTypeId: string;
            startAt: string;
            endAt: string;
            /** @enum {string} */
            status: "free" | "booked";
        };
        ConflictResponse: {
            /** Format: int32 */
            code: number;
            message: string;
        };
        ErrorResponse: {
            /** Format: int32 */
            code: number;
            message: string;
        };
        /**
         * @example {
         *       "code": 404,
         *       "message": "Resource not found"
         *     }
         */
        ErrorResponseExample: {
            /** Format: int32 */
            code: number;
            message: string;
        };
        EventTypeCreateInput: {
            name: string;
            description?: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /**
         * @example {
         *       "name": "Консультация",
         *       "description": "Индивидуальная консультация 30 минут",
         *       "durationMinutes": 30
         *     }
         */
        EventTypeCreateInputExample: {
            name: string;
            description?: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        EventTypeUpdateInput: {
            name?: string;
            description?: string;
            /** Format: int32 */
            durationMinutes?: number;
        };
        /**
         * @example {
         *       "name": "Консультация (обновлённая)",
         *       "durationMinutes": 45
         *     }
         */
        EventTypeUpdateInputExample: {
            name?: string;
            description?: string;
            /** Format: int32 */
            durationMinutes?: number;
        };
        NotFoundResponse: {
            /** Format: int32 */
            code: number;
            message: string;
        };
        SlotGenerateInput: {
            from: string;
            to: string;
            /** Format: int32 */
            slotDurationMinutes?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminEventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreateInput"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Calendar.Domain.EventType"];
                };
            };
        };
    };
    AdminSlots_generate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlotGenerateInput"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Calendar.Domain.Slot"][];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
        };
    };
    AdminEventTypes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeUpdateInput"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Calendar.Domain.EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
        };
    };
    Bookings_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Calendar.Domain.Booking"][];
                };
            };
        };
    };
    Bookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreateInput"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Calendar.Domain.Booking"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictResponse"];
                };
            };
        };
    };
    EventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Calendar.Domain.EventType"][];
                };
            };
        };
    };
    Slots_list: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Calendar.Domain.Slot"][];
                };
            };
        };
    };
    EventTypes_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Calendar.Domain.EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
        };
    };
    OwnerOps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Calendar.Domain.Owner"];
                };
            };
        };
    };
}
